package CalculatorModule;


/**
* CalculatorModule/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Wednesday, May 24, 2023 6:50:38 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
