package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Wednesday, May 24, 2023 6:50:38 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  int divide (int a, int b);
  void shutdown ();
} // interface CalculatorOperations
